apiVersion: v1
kind: Pod
metadata:
    name: aplicacao
spec:
  containers:
    - name: barramento
      image: barramento:latest
      resources:
        limits:
          memory: 256Mi
    - name: mss-pedidos
      image: mss-pedidos:latest
      resources:
        limits:
          memory: 256Mi
    - name: mss-produtos
      image: mss-produtos:latest
      resources:
        limits:
          memory: 256Mi
    - name: frontend
      image: frontend:latest
      resources:
        limits:
          memory: 256Mi